### ISSUE TITLE
new detections are added to next image upon refresh

### ISSUE THREAD

**Issue by swricci** [swricci/labeler#2]
If I add detections on image 1, then close the figure, image 2 appears. I switch back to label mode, add a label, and when I click refresh, the new additions (green dots) from the previous image (image 1) are added to the current image (image 2). The refresh does not change the labeled detection to the blue color - it only adds the green dots. 

If I exit the program after loading image 2, and then restart the program, the labeler works correctly. It only happens if I close image 1 and load image 2 without exiting the program.

**Comment by swricci** [comment]
Example of adding two detections (see image name, and location of additions)
![added](https://github.com/swricci/labeler/assets/47115539/4e561673-4275-4de6-8f40-295da97e969d)

Next image, when switched back to label mode/refresh, the previous detections are visible in the top of this image
![labelMode_next](https://github.com/swricci/labeler/assets/47115539/3e4892ae-024a-4144-b1e2-05a0274b1950)

**Comment by alptezbasaran** [comment]
Thank you for the detailed info. I think we do not clear the `new_detections` list. I am on it!
