### ISSUE TITLE
add class of new detection in add mode

### ISSUE THREAD

**Issue by swricci** [swricci/labeler#5]
Currently we add detections in add mode but there is no way to indicate what class they are (boat, or boat with wake). In add mode, you should be able to click to add a detection and then use a keystroke to indicate the class.

**Comment by alptezbasaran** [comment]
Do you like to 
- click on `a` then a button to pick `boat` or `boat_wake` or
- have individual buttons to go have `add_boat` and `add_wake` options?

**Comment by swricci** [comment]
Whichever is easiest to implement. I just need to be able to class things
in add mode.
